AWA_IMAGES_DIR = '../Animals_with_Attributes2/JPEGImages/'
AWA_LABEL_FILE = '../Animals_with_Attributes2/classes.txt'
AWA_ATTRIBUTE_FILE = '../Animals_with_Attributes2/predicate-matrix-binary.txt'

AWA_TRAIN_CAP = 10 #25900
AWA_TEST_CAP = 10 #11100

CUB_TRAIN_CAP = 0
CUB_TEST_CAP = 0

IN_CHANNELS = 3
IMAGE_SIZE = 224
PATCH_SIZE = 4
INT_DIM = (IMAGE_SIZE // PATCH_SIZE)**2

NUM_CLASSES = 50
CUB_CLASSES = 312
NUM_ATTR = 85
ATTR_EMB = 64
DIM = 768
HEADS = 8
DEPTH = 6
MLP_DIM = 1024
EXPANSION_FACTOR = 4
DROPOUT = 0.1

NORMALIZE_MEAN = 0.0
NORMALIZE_STD = 1.0
MAX_PIXEL_VALUE = 255.0

BATCH_SIZE = 32
EPOCHS = 10
LEARNING_RATE = 1e-4
DEVICE = 'cpu'

ALPHA = 1
BETA = 0
GAMMA = 0